### ISSUE TITLE
Alternative approach

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/focus-indicator#5]
- Update style

``` css
.position-relative {
  position: relative;
}

.focus-indicator {
  /* http://www.puidokas.com/max-z-index/ */
  z-index: 2147483647;
  border-radius: 2px;
  box-shadow: 0 0 2px 4px #50e3c2;
}
```
- No need for `div.focus-indicator`
- On Focus, add  `focus-indicator` class to the `active element` and if active element has `position` as `static` also add `position-relative` class to it.
- On blur remove `focus-indicator` and `position-relative`.
